### PR TITLE
Fix broken link to Geocoding on Rails site

### PR DESCRIPTION
**Pull request by croaky**
I received the following via email:

> Also, I'm thinking of picking up the geocoding book,
> and in the sample:
> http://thoughtbot.com/geocoding-sample.pdf
> 
> there is a link to:
> 
> https://learn.thoughtbot.com/geocodingonrails
> 
> which 301's to a 404: (using a number as verb is weird)
> 
> https://upcase.com/geocodingonrails

### CODE REVIEW

**Comment by croaky** [comment]
@calebthompson Do the other samples have the same issue? Is the process to make a similar commit to each of the books, build them with Paperback, then copy over the sample PDF files into thoughtbot.com's `public` directory?

**Comment by calebhearth** [comment]
That should be the process, yeah. I think in this case I just used `sed`, so the PDF may be wrong.

**Comment by croaky** [comment]
Gotcha. My Paperback install isn't working so can I leave this a task for
you or someone on the Books team?

**Comment by calebhearth** [comment]
Nor is mine, but yes.

**Pull request merged**
